INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (2, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(2, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(2, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(2, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(2, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (3, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(3, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(3, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(3, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(3, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (4, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(4, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(4, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(4, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(4, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (5, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(5, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(5, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(5, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(5, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (6, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(6, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(6, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(6, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(6, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (7, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(7, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(7, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(7, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(7, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (8, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(8, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(8, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(8, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(8, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (9, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(9, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(9, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(9, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(9, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (10, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(10, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(10, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(10, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(10, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (11, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(11, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(11, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(11, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(11, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (12, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(12, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(12, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(12, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(12, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (13, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(13, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(13, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(13, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(13, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');


INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (14, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(14, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(14, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(14, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(14, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (15, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(15, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(15, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(15, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(15, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (16, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(16, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(16, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(16, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(16, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (17, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(17, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(17, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(17, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(17, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (18, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(18, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(18, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(18, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(18, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (19, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(19, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(19, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(19, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(19, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (20, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(20, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(20, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(20, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(20, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (21, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(21, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(21, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(21, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(21, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (22, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(22, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(22, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(22, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(22, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (23, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(23, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(23, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(23, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(23, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (24, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(24, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(24, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(24, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(24, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (25, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(25, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(25, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(25, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(25, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');

INSERT INTO nav.inputdefaultmaster( diseaseid, page, field, fieldtext, tiptext, otherfield)
VALUES (26, 'followupplan', 'activity', 'Medical history and physical exam', 'Visit your doctor every three to six months for the first three years after the first treatment, every six to 12 months for years four and five, and every year thereafter.', 'To check for recurrence and metastasis.'),
(26, 'followupplan', 'activity', 'Post-treatment mammography', 'Schedule a mammogram one year after your first mammogram that led to diagnosis, but no earlier than six months after radiation therapy. Obtain a mammogram every six to 12 months thereafter.','To detect a recurrence of breast cancer.'),
(26, 'followupplan', 'activity', 'Breast self-exam','Perform a breast self-examination every month. This procedure is not a substitute for a mammogram.','To gain familiarity with your breasts so that any changes in texture, including the presence of a lump, can be detected as early as possible.'),
(26, 'followupplan', 'activity', 'Pelvic exam','Continue to visit a gynecologist regularly. If you use tamoxifen, you have a greater risk for developing endometrial cancer (cancer of the lining of the uterus).  Women taking tamoxifen should report any vaginal bleeding to their doctor.','To screen for cervical cancer.'),
(26, 'followupplan', 'activity', 'Genetic counselling','Tell your doctor if there is a history of cancer in your family. The following risk factors may indicate that breast cancer could run in the family:<br/>• Ashkenazi Jewish heritage<br/>• Personal or family history of ovarian cancer<br/>• Any first-degree relative (mother, sister, daughter) diagnosed with breast cancer before age 50<br/>• Two or more first-degree or second-degree relatives (grandparent, aunt, uncle) diagnosed with breast cancer<br/>• Personal or family history of breast cancer in both breasts<br/>• History of breast cancer in a male relative', 'To learn more about potential risks and whether genetic testing for mutations in BRCA1 and BRCA2 might be appropriate.');
